imgw.api_settings:
  type: config_object
  label: 'IMGW Api Settings'
  mapping:
    api_url_meteorogical:
      type: string
      label: 'API base URL for Meteorological data.'
    api_url_hydrological:
      type: string
      label: 'API base URL for Hydrological data.'
